export const USER_REPOSITORY = 'USER_REPOSITORY';
export const THEME_REPOSITORY = 'THEME_REPOSITORY';
export const STORE_REPOSITORY = 'STORE_REPOSITORY';
export const REVIEW_REPOSITORY = 'REVIEW_REPOSITORY';
export const RECORD_REPOSITORY = 'RECORD_REPOSITORY';